---
- name: Install Apache and Copy index.html file
  hosts: all
  become: yes

  vars:
   source_file: ./site/index.html
   dest_file: /var/www/html

  tasks:
  - name: Check and print Linux version
    debug:
     var: ansible_os_family

  - block: #===FOR REDHAT===

     - name: Install Apache
       yum: name=httpd state=latest

     - name: Copy index.html
       copy: src={{source_file}} dest={{dest_file}} mode=0555
       notify: Restart Apache RedHat

     - name: Start Apache and make inable after restart
       service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - block: #===FOR DEBIAN===

     - name: Install Apache For Debian
       yum: name=apache2 state=latest

     - name: Copy index.html
       copy: src={{source_file}} dest={{dest_file}} mode=0555
       notify: Restart Apache Debian

     - name: Start Apache and make inable after restart
       service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"
  


  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted

  - name: Restart Apache Debian
    service: name=apache2 state=restarted
  
