- name: Install Apache and Copy index.html file
# ansible-playbook playbook8.yml -e "HOSTNAME=ALL_SERVERS" 
  hosts: "{{ HOSTNAME }}"
  become: yes

  roles:
   - {role: deploy_apache_web, when: ansible_os_family == 'Linux'}

